FROM oven/bun:1.3.4-alpine AS build
WORKDIR /app

COPY bun.lock .
COPY package.json .
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build



FROM nginx:alpine AS runtime
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
